#!/bin/bash
# セットアップスクリプト（参考用）

echo "🏀 Sports Video Analyzer セットアップ"
echo ""
echo "作成されたファイル:"
echo "✅ DetectionModels.swift"
echo "✅ VideoFrameExtractor.swift"
echo "✅ YOLODetector.swift"
echo "✅ DetectionOverlayView.swift"
echo "✅ VideoAnalysisViewModel.swift"
echo "✅ VideoAnalysisView.swift"
echo "✅ VideoPickerView.swift"
echo "✅ VideoPlayerView.swift"
echo "✅ ContentView.swift"
echo "✅ Info.plist"
echo "✅ README.md"
echo ""
echo "📋 次の手順:"
echo "1. Xcodeでプロジェクトを開く"
echo "2. すべてのファイルがプロジェクトナビゲーターに表示されているか確認"
echo "3. 重複ファイル（VideoPickerView 2.swift等）を削除"
echo "4. Product → Clean Build Folder (⌘⇧K)"
echo "5. Product → Build (⌘B)"
echo "6. Product → Run (⌘R)"
echo ""
echo "🎉 準備完了!"
